# https://help.github.com/articles/configuring-jekyll/

markdown: kramdown

# https://stackoverflow.com/a/25597026
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

encoding: utf-8

url: https://blog.zhstar.win
baseurl: ''

permalink: pretty

paginate: 5

title: '灵河顽石'
tagline: '士不可不坚毅'
description: '联系我 <a href="mailto:{{ site.author.email }}"><br>（youwu at inventati dot org）</a>'

author:
  name: '灵河顽石'
  email: youwu@inventati.org

# Custom vars
version: '壹零壹'
